# k8s/argocd-application.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sk-team-03-backend
  namespace: argocd
  labels:
    app: sk-team-03-backend
    team: sk-team-03
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SKALA-AXelerator/sk-team-03-backend-rev.git  # ← 실제 GitHub 레포지토리 URL로 변경
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sk-team-03
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  info:
    - name: 'Team'
      value: 'SK Team 03'
    - name: 'Environment'
      value: 'Production'
    - name: 'CI/CD'
      value: 'GitHub Actions + ArgoCD'