apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sk-team-03-backend
  namespace: skala-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SKALA-AXelerator/sk-team-03-backend-rev.git  # ✅ 정확함
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sk-team-03
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true