# ingress.yml - 최소 필수 annotations 포함
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: sk-team-03-ingress
  namespace: sk-team-03
spec:
  ingressClassName: public-nginx
  rules:
    - host: sk-team-03.skala25a.project.skala-ai.com
      http:
        paths:
          - backend:
              service:
                name: sk-team-03-backend-service
                port:
                  number: 8080
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: sk-team-03-backend-service
                port:
                  number: 8080
            path: /swagger-ui
            pathType: Prefix
          - backend:
              service:
                name: sk-team-03-backend-service
                port:
                  number: 8080
            path: /api-docs
            pathType: Prefix
  tls:
    - hosts:
        - sk-team-03.skala25a.project.skala-ai.com
      secretName: sk-team-03-tls-secret