# registry-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: sk-team-03-registry-secret
  namespace: sk-team-03
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhbWRwLXJlZ2lzdHJ5LnNrYWxhLWFpLmNvbSI6eyJ1c2VybmFtZSI6IjxVU0VSTkFNRT4iLCJwYXNzd29yZCI6IjxQQVNTV09SRD4iLCJhdXRoIjoiPEJBU0U2NF9BVVRIT1JJWkFUSU9OPiJ9fX0=