
apiVersion: v1
kind: Service
metadata:
  name: sk-team-03-backend-service
  namespace: sk-team-03
  labels:
    app: sk-team-03-spring-backend
    service: spring-backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP